package repository;

import model.*;

import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.sql.*;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

public class H2Database {
    private static final H2Database INSTANCE = new H2Database();

    private static final String JDBC_URL = "jdbc:h2:file:./data/scotiabankdb;DB_CLOSE_DELAY=-1;MODE=MySQL";
    private static final String USER = "sa";
    private static final String PASSWORD = "";

    private H2Database() {
        try {
            Files.createDirectories(Paths.get("data"));
            Class.forName("org.h2.Driver");
            crearTablas();
            cargarDatosIniciales();
        } catch (Exception e) {
            throw new IllegalStateException("No se pudo inicializar la base de datos H2", e);
        }
    }

    public static H2Database getInstance() {
        return INSTANCE;
    }

    private Connection getConnection() throws SQLException {
        return DriverManager.getConnection(JDBC_URL, USER, PASSWORD);
    }

    private void crearTablas() throws SQLException {
        try (Connection cn = getConnection(); Statement st = cn.createStatement()) {
            st.execute("CREATE TABLE IF NOT EXISTS usuarios (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    nombres VARCHAR(100) NOT NULL,\n" +
"    apellidos VARCHAR(100) NOT NULL,\n" +
"    correo VARCHAR(120) NOT NULL UNIQUE,\n" +
"    password VARCHAR(100) NOT NULL,\n" +
"    rol VARCHAR(40) NOT NULL,\n" +
"    activo BOOLEAN NOT NULL\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS clientes (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    dni VARCHAR(15) NOT NULL UNIQUE,\n" +
"    nombres VARCHAR(100) NOT NULL,\n" +
"    apellidos VARCHAR(100) NOT NULL,\n" +
"    correo VARCHAR(120),\n" +
"    telefono VARCHAR(20),\n" +
"    direccion VARCHAR(180),\n" +
"    ocupacion VARCHAR(100),\n" +
"    ingresos_mensuales DECIMAL(12,2),\n" +
"    estado VARCHAR(20) NOT NULL,\n" +
"    fecha_registro TIMESTAMP NOT NULL\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS productos (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    nombre VARCHAR(120) NOT NULL,\n" +
"    tipo VARCHAR(40) NOT NULL,\n" +
"    descripcion VARCHAR(250),\n" +
"    tasa_base DECIMAL(5,2),\n" +
"    activo BOOLEAN NOT NULL\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS solicitudes (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    codigo VARCHAR(40) NOT NULL UNIQUE,\n" +
"    cliente_id INT NOT NULL,\n" +
"    producto_id INT NOT NULL,\n" +
"    usuario_id INT,\n" +
"    monto_solicitado DECIMAL(12,2) NOT NULL,\n" +
"    plazo_meses INT NOT NULL,\n" +
"    finalidad VARCHAR(250) NOT NULL,\n" +
"    estado VARCHAR(30) NOT NULL,\n" +
"    fecha_registro TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (cliente_id) REFERENCES clientes(id),\n" +
"    FOREIGN KEY (producto_id) REFERENCES productos(id),\n" +
"    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS evaluaciones (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    solicitud_id INT NOT NULL,\n" +
"    analista_id INT NOT NULL,\n" +
"    puntaje_crediticio INT NOT NULL,\n" +
"    nivel_riesgo VARCHAR(20) NOT NULL,\n" +
"    ingreso_validado DECIMAL(12,2) NOT NULL,\n" +
"    resultado VARCHAR(30) NOT NULL,\n" +
"    comentario VARCHAR(250),\n" +
"    fecha_evaluacion TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id),\n" +
"    FOREIGN KEY (analista_id) REFERENCES usuarios(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS operaciones (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    cliente_id INT NOT NULL,\n" +
"    solicitud_id INT,\n" +
"    usuario_id INT,\n" +
"    tipo_operacion VARCHAR(60) NOT NULL,\n" +
"    monto DECIMAL(12,2) NOT NULL,\n" +
"    descripcion VARCHAR(250),\n" +
"    estado VARCHAR(30) NOT NULL,\n" +
"    fecha_operacion TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (cliente_id) REFERENCES clientes(id),\n" +
"    FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id),\n" +
"    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS movimientos (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    operacion_id INT NOT NULL,\n" +
"    tipo_movimiento VARCHAR(60) NOT NULL,\n" +
"    monto DECIMAL(12,2) NOT NULL,\n" +
"    saldo_resultante DECIMAL(12,2),\n" +
"    fecha_movimiento TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (operacion_id) REFERENCES operaciones(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS comprobantes (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    operacion_id INT NOT NULL UNIQUE,\n" +
"    serie VARCHAR(10) NOT NULL,\n" +
"    numero VARCHAR(20) NOT NULL,\n" +
"    tipo_comprobante VARCHAR(60) NOT NULL,\n" +
"    fecha_emision TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (operacion_id) REFERENCES operaciones(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS notificaciones (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    cliente_id INT NOT NULL,\n" +
"    solicitud_id INT,\n" +
"    canal VARCHAR(30) NOT NULL,\n" +
"    asunto VARCHAR(120) NOT NULL,\n" +
"    mensaje VARCHAR(300) NOT NULL,\n" +
"    estado_envio VARCHAR(30) NOT NULL,\n" +
"    fecha_envio TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (cliente_id) REFERENCES clientes(id),\n" +
"    FOREIGN KEY (solicitud_id) REFERENCES solicitudes(id)\n" +
")\n");
            st.execute("CREATE TABLE IF NOT EXISTS auditorias (\n" +
"    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n" +
"    usuario_id INT,\n" +
"    modulo VARCHAR(80) NOT NULL,\n" +
"    accion VARCHAR(100) NOT NULL,\n" +
"    descripcion VARCHAR(300),\n" +
"    fecha_hora TIMESTAMP NOT NULL,\n" +
"    FOREIGN KEY (usuario_id) REFERENCES usuarios(id)\n" +
")\n");
        }
    }

    private void cargarDatosIniciales() throws SQLException {
        if (count("usuarios") == 0) {
            insertUsuario("Admin", "Sistema", "admin@scotia.com", "123456", Rol.ADMINISTRADOR, true);
            insertUsuario("Ana", "Asesora", "asesor@scotia.com", "123456", Rol.ASESOR_BANCARIO, true);
            insertUsuario("Carlos", "Cliente", "cliente@scotia.com", "123456", Rol.CLIENTE, true);
            insertUsuario("Lucia", "Analista", "analista@scotia.com", "123456", Rol.ANALISTA_CREDITO, true);
            insertUsuario("Gerardo", "Gerente", "gerente@scotia.com", "123456", Rol.GERENTE, true);
        }
        if (count("clientes") == 0) {
            insertCliente("70000111", "María", "Torres", "maria.torres@email.com", "999111222", "Av. Principal 123", "Contadora", new BigDecimal("4500.00"), "ACTIVO");
            insertCliente("70000222", "Luis", "Ramírez", "luis.ramirez@email.com", "999333444", "Jr. Lima 456", "Comerciante", new BigDecimal("3200.00"), "ACTIVO");
            insertCliente("70000333", "Sofía", "Herrera", "sofia.herrera@email.com", "999555666", "Calle Los Pinos 789", "Diseñadora", new BigDecimal("2800.00"), "ACTIVO");
        }
        if (count("productos") == 0) {
            insertProducto("Préstamo Personal", TipoProducto.PRESTAMO, "Crédito de libre disponibilidad", new BigDecimal("14.50"), true);
            insertProducto("Tarjeta Crédito Clásica", TipoProducto.TARJETA_CREDITO, "Tarjeta para consumos nacionales", new BigDecimal("35.00"), true);
            insertProducto("Tarjeta Crédito Gold", TipoProducto.TARJETA_CREDITO, "Tarjeta con beneficios premium", new BigDecimal("42.00"), true);
        }
    }

    private int count(String table) throws SQLException {
        try (Connection cn = getConnection(); Statement st = cn.createStatement(); ResultSet rs = st.executeQuery("SELECT COUNT(*) FROM " + table)) {
            rs.next();
            return rs.getInt(1);
        }
    }

    private Timestamp now() {
        return Timestamp.valueOf(LocalDateTime.now());
    }

    public int total(String table) {
        try {
            return count(table);
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo contar registros de " + table, e);
        }
    }

    // USUARIOS / SEGURIDAD
    public Usuario insertUsuario(String nombres, String apellidos, String correo, String password, Rol rol, boolean activo) {
        String sql = "INSERT INTO usuarios(nombres, apellidos, correo, password, rol, activo) VALUES(?,?,?,?,?,?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, nombres);
            ps.setString(2, apellidos);
            ps.setString(3, correo);
            ps.setString(4, password);
            ps.setString(5, rol.name());
            ps.setBoolean(6, activo);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new Usuario(keys.getInt(1), nombres, apellidos, correo, password, rol, activo);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar usuario", e);
        }
    }

    public Optional<Usuario> findUsuarioByCredentials(String correo, String password) {
        String sql = "SELECT * FROM usuarios WHERE LOWER(correo)=LOWER(?) AND password=? AND activo=TRUE";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, correo.trim());
            ps.setString(2, password);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapUsuario(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo validar usuario", e);
        }
    }

    public Optional<Usuario> findUsuarioById(Integer id) {
        if (id == null) return Optional.empty();
        String sql = "SELECT * FROM usuarios WHERE id=?";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapUsuario(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar usuario", e);
        }
    }

    public List<Usuario> listUsuarios() {
        List<Usuario> list = new ArrayList<>();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM usuarios ORDER BY id"); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(mapUsuario(rs));
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar usuarios", e);
        }
    }

    public void updateUsuarioRol(int idUsuario, Rol rol) {
        execute("UPDATE usuarios SET rol=? WHERE id=?", rol.name(), idUsuario);
    }

    public void updateUsuarioActivo(int idUsuario, boolean activo) {
        execute("UPDATE usuarios SET activo=? WHERE id=?", activo, idUsuario);
    }

    private Usuario mapUsuario(ResultSet rs) throws SQLException {
        return new Usuario(rs.getInt("id"), rs.getString("nombres"), rs.getString("apellidos"), rs.getString("correo"),
                rs.getString("password"), Rol.valueOf(rs.getString("rol")), rs.getBoolean("activo"));
    }

    // CLIENTES
    public Cliente insertCliente(String dni, String nombres, String apellidos, String correo, String telefono,
                                 String direccion, String ocupacion, BigDecimal ingresos, String estado) {
        String sql = "INSERT INTO clientes(dni, nombres, apellidos, correo, telefono, direccion, ocupacion, ingresos_mensuales, estado, fecha_registro)\n" +
"VALUES(?,?,?,?,?,?,?,?,?,?)\n";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, dni);
            ps.setString(2, nombres);
            ps.setString(3, apellidos);
            ps.setString(4, correo);
            ps.setString(5, telefono);
            ps.setString(6, direccion);
            ps.setString(7, ocupacion);
            ps.setBigDecimal(8, ingresos);
            ps.setString(9, estado);
            ps.setTimestamp(10, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new Cliente(keys.getInt(1), dni, nombres, apellidos, correo, telefono, direccion, ocupacion, ingresos, estado);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar cliente", e);
        }
    }

    public void updateCliente(Cliente cliente) {
        String sql = "UPDATE clientes SET nombres=?, apellidos=?, correo=?, telefono=?, direccion=?, ocupacion=?, ingresos_mensuales=?, estado=?\n" +
"WHERE id=?\n";
        execute(sql, cliente.getNombres(), cliente.getApellidos(), cliente.getCorreo(), cliente.getTelefono(), cliente.getDireccion(),
                cliente.getOcupacion(), cliente.getIngresosMensuales(), cliente.getEstado(), cliente.getId());
    }

    public Optional<Cliente> findClienteByDni(String dni) {
        String sql = "SELECT * FROM clientes WHERE LOWER(dni)=LOWER(?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, dni.trim());
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapCliente(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar cliente", e);
        }
    }

    public Optional<Cliente> findClienteById(Integer id) {
        if (id == null) return Optional.empty();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM clientes WHERE id=?")) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapCliente(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar cliente", e);
        }
    }

    public List<Cliente> listClientes() {
        List<Cliente> list = new ArrayList<>();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM clientes ORDER BY id"); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(mapCliente(rs));
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar clientes", e);
        }
    }

    public List<Cliente> searchClientes(String texto) {
        if (texto == null || texto.trim().isEmpty()) return listClientes();
        List<Cliente> list = new ArrayList<>();
        String q = "%" + texto.trim().toLowerCase() + "%";
        String sql = "SELECT * FROM clientes WHERE LOWER(dni) LIKE ? OR LOWER(nombres) LIKE ? OR LOWER(apellidos) LIKE ? ORDER BY id";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            ps.setString(1, q); ps.setString(2, q); ps.setString(3, q);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapCliente(rs));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron buscar clientes", e);
        }
    }

    private Cliente mapCliente(ResultSet rs) throws SQLException {
        return new Cliente(rs.getInt("id"), rs.getString("dni"), rs.getString("nombres"), rs.getString("apellidos"),
                rs.getString("correo"), rs.getString("telefono"), rs.getString("direccion"), rs.getString("ocupacion"),
                rs.getBigDecimal("ingresos_mensuales"), rs.getString("estado"));
    }

    // PRODUCTOS
    public ProductoFinanciero insertProducto(String nombre, TipoProducto tipo, String descripcion, BigDecimal tasaBase, boolean activo) {
        String sql = "INSERT INTO productos(nombre, tipo, descripcion, tasa_base, activo) VALUES(?,?,?,?,?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, nombre);
            ps.setString(2, tipo.name());
            ps.setString(3, descripcion);
            ps.setBigDecimal(4, tasaBase);
            ps.setBoolean(5, activo);
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new ProductoFinanciero(keys.getInt(1), nombre, tipo, descripcion, tasaBase, activo);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar producto", e);
        }
    }

    public Optional<ProductoFinanciero> findProductoById(Integer id) {
        if (id == null) return Optional.empty();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM productos WHERE id=?")) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapProducto(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar producto", e);
        }
    }

    public List<ProductoFinanciero> listProductosActivos() {
        List<ProductoFinanciero> list = new ArrayList<>();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM productos WHERE activo=TRUE ORDER BY id"); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) list.add(mapProducto(rs));
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar productos", e);
        }
    }

    private ProductoFinanciero mapProducto(ResultSet rs) throws SQLException {
        return new ProductoFinanciero(rs.getInt("id"), rs.getString("nombre"), TipoProducto.valueOf(rs.getString("tipo")),
                rs.getString("descripcion"), rs.getBigDecimal("tasa_base"), rs.getBoolean("activo"));
    }

    // SOLICITUDES
    public SolicitudCrediticia insertSolicitud(String codigo, Cliente cliente, ProductoFinanciero producto, Usuario usuario,
                                               BigDecimal monto, int plazoMeses, String finalidad) {
        String sql = "INSERT INTO solicitudes(codigo, cliente_id, producto_id, usuario_id, monto_solicitado, plazo_meses, finalidad, estado, fecha_registro)\n" +
"VALUES(?,?,?,?,?,?,?,?,?)\n";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setString(1, codigo);
            ps.setInt(2, cliente.getId());
            ps.setInt(3, producto.getId());
            if (usuario == null) ps.setNull(4, Types.INTEGER); else ps.setInt(4, usuario.getId());
            ps.setBigDecimal(5, monto);
            ps.setInt(6, plazoMeses);
            ps.setString(7, finalidad);
            ps.setString(8, EstadoSolicitud.PENDIENTE.name());
            ps.setTimestamp(9, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new SolicitudCrediticia(keys.getInt(1), codigo, cliente, producto, usuario, monto, plazoMeses, finalidad);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar solicitud", e);
        }
    }

    public void updateSolicitudEstado(int idSolicitud, EstadoSolicitud estado) {
        execute("UPDATE solicitudes SET estado=? WHERE id=?", estado.name(), idSolicitud);
    }

    public Optional<SolicitudCrediticia> findSolicitudById(Integer id) {
        if (id == null) return Optional.empty();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM solicitudes WHERE id=?")) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapSolicitud(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar solicitud", e);
        }
    }

    public List<SolicitudCrediticia> listSolicitudes() {
        return listSolicitudesBySql("SELECT * FROM solicitudes ORDER BY id", null);
    }

    public List<SolicitudCrediticia> listSolicitudesByEstado(EstadoSolicitud estado) {
        return listSolicitudesBySql("SELECT * FROM solicitudes WHERE estado=? ORDER BY id", estado.name());
    }

    public List<SolicitudCrediticia> listSolicitudesByCliente(Cliente cliente) {
        if (cliente == null) return java.util.Collections.emptyList();
        return listSolicitudesBySql("SELECT * FROM solicitudes WHERE cliente_id=? ORDER BY id", cliente.getId());
    }

    private List<SolicitudCrediticia> listSolicitudesBySql(String sql, Object param) {
        List<SolicitudCrediticia> list = new ArrayList<>();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            if (param instanceof String) ps.setString(1, (String) param);
            if (param instanceof Integer) ps.setInt(1, (Integer) param);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapSolicitud(rs));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar solicitudes", e);
        }
    }

    private SolicitudCrediticia mapSolicitud(ResultSet rs) throws SQLException {
        Cliente cliente = findClienteById(rs.getInt("cliente_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
        ProductoFinanciero producto = findProductoById(rs.getInt("producto_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
        Usuario usuario = findUsuarioById((Integer) rs.getObject("usuario_id")).orElse(null);
        SolicitudCrediticia solicitud = new SolicitudCrediticia(rs.getInt("id"), rs.getString("codigo"), cliente, producto, usuario,
                rs.getBigDecimal("monto_solicitado"), rs.getInt("plazo_meses"), rs.getString("finalidad"));
        solicitud.setEstado(EstadoSolicitud.valueOf(rs.getString("estado")));
        return solicitud;
    }

    // EVALUACIONES
    public EvaluacionCrediticia insertEvaluacion(SolicitudCrediticia solicitud, Usuario analista, int puntaje, NivelRiesgo riesgo,
                                                 BigDecimal ingresoValidado, EstadoSolicitud resultado, String comentario) {
        String sql = "INSERT INTO evaluaciones(solicitud_id, analista_id, puntaje_crediticio, nivel_riesgo, ingreso_validado, resultado, comentario, fecha_evaluacion)\n" +
"VALUES(?,?,?,?,?,?,?,?)\n";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, solicitud.getId());
            ps.setInt(2, analista.getId());
            ps.setInt(3, puntaje);
            ps.setString(4, riesgo.name());
            ps.setBigDecimal(5, ingresoValidado);
            ps.setString(6, resultado.name());
            ps.setString(7, comentario);
            ps.setTimestamp(8, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new EvaluacionCrediticia(keys.getInt(1), solicitud, analista, puntaje, riesgo, ingresoValidado, resultado, comentario);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar evaluación", e);
        }
    }

    public List<EvaluacionCrediticia> listEvaluaciones() {
        List<EvaluacionCrediticia> list = new ArrayList<>();
        String sql = "SELECT * FROM evaluaciones ORDER BY id";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                SolicitudCrediticia solicitud = findSolicitudById(rs.getInt("solicitud_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
                Usuario analista = findUsuarioById(rs.getInt("analista_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
                list.add(new EvaluacionCrediticia(rs.getInt("id"), solicitud, analista, rs.getInt("puntaje_crediticio"),
                        NivelRiesgo.valueOf(rs.getString("nivel_riesgo")), rs.getBigDecimal("ingreso_validado"),
                        EstadoSolicitud.valueOf(rs.getString("resultado")), rs.getString("comentario")));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar evaluaciones", e);
        }
    }

    // NOTIFICACIONES
    public Notificacion insertNotificacion(Cliente cliente, SolicitudCrediticia solicitud, String canal, String asunto, String mensaje) {
        String sql = "INSERT INTO notificaciones(cliente_id, solicitud_id, canal, asunto, mensaje, estado_envio, fecha_envio) VALUES(?,?,?,?,?,?,?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, cliente.getId());
            if (solicitud == null) ps.setNull(2, Types.INTEGER); else ps.setInt(2, solicitud.getId());
            ps.setString(3, canal);
            ps.setString(4, asunto);
            ps.setString(5, mensaje);
            ps.setString(6, "ENVIADA");
            ps.setTimestamp(7, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new Notificacion(keys.getInt(1), cliente, solicitud, canal, asunto, mensaje);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar notificación", e);
        }
    }

    public List<Notificacion> listNotificaciones() {
        List<Notificacion> list = new ArrayList<>();
        String sql = "SELECT * FROM notificaciones ORDER BY id";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Cliente cliente = findClienteById(rs.getInt("cliente_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
                SolicitudCrediticia solicitud = findSolicitudById((Integer) rs.getObject("solicitud_id")).orElse(null);
                list.add(new Notificacion(rs.getInt("id"), cliente, solicitud, rs.getString("canal"), rs.getString("asunto"), rs.getString("mensaje")));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar notificaciones", e);
        }
    }

    // OPERACIONES
    public OperacionBancaria insertOperacion(Cliente cliente, SolicitudCrediticia solicitud, Usuario usuario, String tipoOperacion,
                                             BigDecimal monto, String descripcion) {
        String sql = "INSERT INTO operaciones(cliente_id, solicitud_id, usuario_id, tipo_operacion, monto, descripcion, estado, fecha_operacion)\n" +
"VALUES(?,?,?,?,?,?,?,?)\n";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, cliente.getId());
            if (solicitud == null) ps.setNull(2, Types.INTEGER); else ps.setInt(2, solicitud.getId());
            if (usuario == null) ps.setNull(3, Types.INTEGER); else ps.setInt(3, usuario.getId());
            ps.setString(4, tipoOperacion);
            ps.setBigDecimal(5, monto);
            ps.setString(6, descripcion);
            ps.setString(7, "REGISTRADA");
            ps.setTimestamp(8, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new OperacionBancaria(keys.getInt(1), cliente, solicitud, usuario, tipoOperacion, monto, descripcion);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar operación", e);
        }
    }

    public void insertMovimiento(OperacionBancaria operacion, String tipoMovimiento, BigDecimal monto, BigDecimal saldoResultante) {
        execute("INSERT INTO movimientos(operacion_id, tipo_movimiento, monto, saldo_resultante, fecha_movimiento) VALUES(?,?,?,?,?)",
                operacion.getId(), tipoMovimiento, monto, saldoResultante, now());
    }

    public ComprobanteElectronico insertComprobante(OperacionBancaria operacion, String serie, String numero, String tipoComprobante) {
        String sql = "INSERT INTO comprobantes(operacion_id, serie, numero, tipo_comprobante, fecha_emision) VALUES(?,?,?,?,?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
            ps.setInt(1, operacion.getId());
            ps.setString(2, serie);
            ps.setString(3, numero);
            ps.setString(4, tipoComprobante);
            ps.setTimestamp(5, now());
            ps.executeUpdate();
            try (ResultSet keys = ps.getGeneratedKeys()) {
                keys.next();
                return new ComprobanteElectronico(keys.getInt(1), operacion, serie, numero, tipoComprobante);
            }
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo insertar comprobante", e);
        }
    }

    public List<OperacionBancaria> listOperaciones() {
        return listOperacionesBySql("SELECT * FROM operaciones ORDER BY id", null);
    }

    public List<OperacionBancaria> listOperacionesByCliente(Cliente cliente) {
        if (cliente == null) return java.util.Collections.emptyList();
        return listOperacionesBySql("SELECT * FROM operaciones WHERE cliente_id=? ORDER BY id", cliente.getId());
    }

    private List<OperacionBancaria> listOperacionesBySql(String sql, Integer clienteId) {
        List<OperacionBancaria> list = new ArrayList<>();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            if (clienteId != null) ps.setInt(1, clienteId);
            try (ResultSet rs = ps.executeQuery()) {
                while (rs.next()) list.add(mapOperacion(rs));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar operaciones", e);
        }
    }

    private Optional<OperacionBancaria> findOperacionById(Integer id) {
        if (id == null) return Optional.empty();
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement("SELECT * FROM operaciones WHERE id=?")) {
            ps.setInt(1, id);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) return Optional.of(mapOperacion(rs));
            }
            return Optional.empty();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo buscar operación", e);
        }
    }

    private OperacionBancaria mapOperacion(ResultSet rs) throws SQLException {
        Cliente cliente = findClienteById(rs.getInt("cliente_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
        SolicitudCrediticia solicitud = findSolicitudById((Integer) rs.getObject("solicitud_id")).orElse(null);
        Usuario usuario = findUsuarioById((Integer) rs.getObject("usuario_id")).orElse(null);
        return new OperacionBancaria(rs.getInt("id"), cliente, solicitud, usuario, rs.getString("tipo_operacion"),
                rs.getBigDecimal("monto"), rs.getString("descripcion"));
    }

    public List<ComprobanteElectronico> listComprobantes() {
        List<ComprobanteElectronico> list = new ArrayList<>();
        String sql = "SELECT * FROM comprobantes ORDER BY id";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                OperacionBancaria operacion = findOperacionById(rs.getInt("operacion_id")).orElseThrow(() -> new IllegalStateException("Registro relacionado no encontrado"));
                list.add(new ComprobanteElectronico(rs.getInt("id"), operacion, rs.getString("serie"), rs.getString("numero"), rs.getString("tipo_comprobante")));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar comprobantes", e);
        }
    }

    // AUDITORÍA
    public void insertAuditoria(Usuario usuario, String modulo, String accion, String descripcion) {
        Integer idUsuario = usuario == null ? null : usuario.getId();
        String sql = "INSERT INTO auditorias(usuario_id, modulo, accion, descripcion, fecha_hora) VALUES(?,?,?,?,?)";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            if (idUsuario == null) ps.setNull(1, Types.INTEGER); else ps.setInt(1, idUsuario);
            ps.setString(2, modulo);
            ps.setString(3, accion);
            ps.setString(4, descripcion);
            ps.setTimestamp(5, now());
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudo registrar auditoría", e);
        }
    }

    public List<Auditoria> listAuditorias() {
        List<Auditoria> list = new ArrayList<>();
        String sql = "SELECT * FROM auditorias ORDER BY id DESC";
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Usuario usuario = findUsuarioById((Integer) rs.getObject("usuario_id")).orElse(null);
                list.add(new Auditoria(rs.getInt("id"), usuario, rs.getString("modulo"), rs.getString("accion"), rs.getString("descripcion")));
            }
            return list;
        } catch (SQLException e) {
            throw new IllegalStateException("No se pudieron listar auditorías", e);
        }
    }

    private void execute(String sql, Object... params) {
        try (Connection cn = getConnection(); PreparedStatement ps = cn.prepareStatement(sql)) {
            for (int i = 0; i < params.length; i++) {
                ps.setObject(i + 1, params[i]);
            }
            ps.executeUpdate();
        } catch (SQLException e) {
            throw new IllegalStateException("Error ejecutando SQL: " + sql, e);
        }
    }
}
